# Kapua configuration file
# v0.0.1

server:
  ip4_address: 0.0.0.0
  port: 11840

local_discovery: 
  enable: true
  ip4_address: 0.0.0.0
  port: 11840
  interval: 1m

trackers:
  enable: true
  servers:
    - nzl.tracker.kapua.org.nz
    - tracker.blackraven.co.nz

logging:
  level: debug
