# Kapua configuration file
# v0.0.1

server:
  ip4_address: 0.0.0.0
  port: 11840

  key_files:
    private: snakeoil.pem
    public: snakeoil_pub.pem

local_discovery: 
  enable: false
  ip4_address: 0.0.0.0
  port: 11840
  interval: 10s

trackers:
  enable: true
  servers:
    - nzl.tracker.kapua.org.nz
    - tracker.blackraven.co.nz

memcached:
  enable: true
  ip4_address: 0.0.0.0
  port: 11211
  extensions: true
  connection_limit: 20
  inactivity_timeout: 30s
  
logging:
  level: debug
