# Kapua configuration file
# v0.0.1



address:
  ip4_address: 0.0.0.0
  port: 11840

local_discovery: 
  enable: true
  ip4_address: 0.0.0.0
  port: 11840
  interval: 1m

hints:
  enable: true
  servers:
    - hint.kapua.org.nz
    - hint.blackraven.co.nz

logging:
  level: debug
