version: 2.1

executors:
  default:
    docker:
      - image: ubuntu:latest

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install required dependencies
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential wget cmake libssl-dev libyaml-cpp-dev libcurl4-openssl-dev
            wget https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2
            tar -xjf boost_1_83_0.tar.bz2
            cd boost_1_83_0
            ./bootstrap.sh --prefix=/usr/local
            ./b2 install

      # Build kapua_test
      - run:
          name: Build kapua_test
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Run tests
      - run:
          name: Run Tests
          command: |
            cd build
            ctest --output-on-failure

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
