version: 2.1

executors:
  default:
    docker:
      - image: ubuntu-2204:2023.10.1

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install required dependencies
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essentials libboost-all-dev libssl-dev libyaml-cpp-dev libcurl4-openssl-dev

      # Build kapua_test
      - run:
          name: Build kapua_test
          command: |
            mkdir build
            cd build
            cmake ..
            make

      # Run tests
      - run:
          name: Run Tests
          command: |
            cd build
            ctest --output-on-failure

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
